### ISSUE TITLE
dbus timeout if no notification deamon

### ISSUE THREAD

**Issue by makohoek** [jeremy-compostella/device-control#4]
Use case:
use `emacs -nw` on a remote server, with no notification deamon running

when using device control, emacs hangs for ~20seconds after each command. This is because device-control tries to notify the desktop using the `notifications` package.
In the emacs `*Messages*` buffer, we can see the following:

```
Error: (dbus-error "call timed out")
```

Note: this is not a device-control specific problem, as this is how `notifications.el` behaves.

As a work-around, i have installed `dunst` in my environment. The hanging goes away.

Do you want to support this use case? Or should it be documented that it is a pre-requisite to have a notification deamon installed when using this module.
Alternatively, maybe it is possible to change dbus default timeout so that emacs does not hang that long.

Info about Desktop notifications:
https://wiki.archlinux.org/index.php/Desktop_notifications#Built-in

**Comment by jeremy-compostella** [comment]
I am trying to see if there is a way to detect the situation.  Could you evaluate (notifications-get-server-information) on this remote server and tell me if the it does return nil and it timeout of not ?

**Comment by makohoek** [comment]
I confirm that evaluating `(notifications-get-server-information)` returns nil. (I uninstalled `dunst` and rebooted the server before evaluation)

Since the reboot, i don't reproduce the timeout issue anymore. I still get error messages from `notifications.el` :
```
Error: (dbus-error "The name org.freedesktop.Notifications was not provided by any .service files") [2 times]
```

I do still think that this issue is a corner case and I am not sure if this should be handled by this module or not.

On a similar note, if emacs is not compiled with `dbus` support (like on MacOS), the commands fail as well:
```
dbus-call-method: peculiar error: "Emacs not compiled with dbus support"
```

**Comment by makohoek** [comment]
For emacs dbus support, we can test with 
```elisp
;; returns nil if 'dbus-compiled-version is void
 (boundp 'dbus-compiled-version)
```

https://www.gnu.org/software/emacs/manual/html_mono/dbus.html

**Comment by jeremy-compostella** [comment]
Or (featurep 'dbusbind) right ?

**Comment by jeremy-compostella** [comment]
What about ?
```
modified   device-control.el
@@ -139,13 +139,14 @@ its functions available to device control."
 (defun dctrl-headline-msg (msg)
   (when dctrl-prev-notif-id
     (notifications-close-notification dctrl-prev-notif-id))
-  (setq dctrl-prev-notif-id
-	(apply 'notifications-notify
-	       :app-name "DeviceControl"
-	       :title "Device control"
-	       :body msg
-	       (when dctrl-icon
-		 (list :app-icon dctrl-icon))))
+  (when (and (featurep 'dbusbind) (notifications-get-server-information))
+    (setq dctrl-prev-notif-id
+	  (apply 'notifications-notify
+		 :app-name "DeviceControl"
+		 :title "Device control"
+		 :body msg
+		 (when dctrl-icon
+		   (list :app-icon dctrl-icon)))))
   (dctrl-msg msg 'success))
 
 (defun dctrl-error (msg)
```
`

**Comment by makohoek** [comment]
`(featurep 'dbusbind)` returns `nil` as well.

Also, the diff you posted works for me. 

I will update my patch with your diff and add your signed-off as well.
